In [5]:
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 12 15:29:25 2018

@author: purandur
"""

#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random as rd
from collections import defaultdict
import matplotlib.cm as cm

dataset=pd.read_csv('tfidf_of_paras.csv')
X = dataset.iloc[:,1:].values
X = np.nan_to_num(X)
# print(X)
K=5
m=X.shape[0]
dim = X.shape[1]
Centroids=np.array([]).reshape(dim,0)

# print(Centroids)
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
# print(mean,std)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[8.10902896e-05 3.25383305e-04 2.94718910e-04 ... 6.39693356e-04
 2.09369676e-04 1.34923339e-04] [0.00196299 0.0078767  0.00713439 ... 0.00929132 0.0050683  0.00326615]


In [12]:
#step 1
for i in range(K):
    rand=rd.randint(0,m-1)
    Centroids = np.c_[Centroids,X[rand]]
    

#step2
num_iter=100
Output=defaultdict()
Output={}
for n in range(num_iter):
    #step 2.a
    EuclidianDistance=np.array([]).reshape(m,0)
    for k in range(K):
        tempDist=np.sum((X-Centroids[:,k])**2,axis=1)
        EuclidianDistance=np.c_[EuclidianDistance,tempDist]
        
    C=np.argmin(EuclidianDistance,axis=1)+1
    #step 2.b
    Y={}
    for k in range(K):
        Y[k+1]=np.array([]).reshape(dim,0)
    for i in range(m):
        Y[C[i]]=np.c_[Y[C[i]],X[i]]
     
    for k in range(K):
        Y[k+1]=Y[k+1].T
        
        
    for k in range(K):
        Centroids[:,k]=np.mean(Y[k+1],axis=0)
        
    Output=Y
print (C) #clusters assigned